export { Button } from "./button";
export type { ButtonProps, ButtonVariant } from "./button";
export { AppProvider } from "./AppProvider";
export { tamaguiConfig, colors } from "./tamagui.config";
export type { AppConfig } from "./tamagui.config";
export { Text } from "./Text";
export type { TextProps, TextVariant } from "./Text";
export { Switch } from "./Switch";
export type { SwitchProps } from "./Switch";
export { PageContainer } from "./PageContainer";
export type { PageContainerProps } from "./PageContainer";
export { TextInput } from "./TextInput";
export type { TextInputProps } from "./TextInput";
export { YStack, XStack, View, useTheme } from "tamagui";
export { TypeIcon } from "./TypeIcon";
export { Computer, Settings2, ChevronLeft } from "@tamagui/lucide-icons";
